# Generated by Django 3.2.13 on 2022-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(max_length=50)),
                ('parent_email', models.EmailField(max_length=100, unique=True)),
                ('class_name', models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade1', 'Grade1'), ('Grade2', 'Grade2'), ('Grade3', 'Grade3'), ('Grade4', 'Grade4'), ('Grade5', 'Grade5'), ('Grade6', 'Grade6'), ('Grade7', 'Grade7'), ('Grade8', 'Grade8')], default='PP1', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('stud_pic', models.ImageField(blank=True, upload_to='administration/students')),
            ],
        ),
    ]
